before_script:
    - cd exampleSite

stages:
    - build
    - deploy

build:
    image: registry.gitlab.com/pages/hugo/hugo_extended:latest
    stage: build
    script:
        - hugo --themesDir ../../ -t "hugo-theme-chunky-poster"
    artifacts:
        paths:
            - exampleSite/public
    only:
        - master

deploy:
    image: node:latest
    stage: deploy
    before_script:
        - npm i -g netlify-cli
    script:
        - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod --message "Deploy via Gitlab Pipelines."
    only:
        - master
    dependencies:
        - build
